import type { Metadata } from "next";

import { ClerkProvider } from "@clerk/nextjs";
import { Poppins } from "next/font/google";
import React from "react";

import "../globals.css";

const poppins = Poppins({
  subsets: ["latin-ext"],
  weight: ["400", "500", "700", "900"],
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider afterSignOutUrl="/sign-in">
        <body className={poppins.className}>
          <main className="h-[calc(100vh-5rem)]">
            <div className="flex h-full justify-between bg-gray-400">
              <div className="h-full bg-auth-bg bg-contain bg-center bg-no-repeat xl:w-2/3" />
              <div className="flex items-center justify-center xl:w-1/3">
                {children}
              </div>
            </div>
          </main>
          <footer className="relative flex h-20 w-full items-center justify-between border-t bg-gray-100 px-12">
            <div className="flex w-full items-center justify-between">
              <div>BunkieGot®</div>
              <div className="text-sm text-gray-500">
                {new Date().getFullYear()}. All rights reserved.
              </div>
            </div>
          </footer>
        </body>
      </ClerkProvider>
    </html>
  );
}
