import './globals.css';

import { ClerkProvider, UserButton } from '@clerk/nextjs';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import Link from 'next/link';
import React from 'react';

const poppins = Poppins({
  subsets: ['latin-ext'],
  weight: ['400', '500', '700', '900'],
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  modal,
  children,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className={poppins.className}>
          <div className="flex h-lvh flex-col justify-between">
            <header className="border-b bg-background px-12 py-6">
              <div className="flex w-full items-center justify-between">
                <Link href="/">BunkieGot</Link>
                <UserButton showName />
              </div>
            </header>
            <main className="container mx-auto">
              {modal}
              {children}
            </main>
            <footer className="border-t bg-background px-12 py-6">
              <div className="flex w-full items-center justify-between">
                Footer
              </div>
            </footer>
          </div>
        </body>
      </ClerkProvider>
    </html>
  );
}
