import './globals.css';

import { UserProvider } from '@auth0/nextjs-auth0/client';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import React from 'react';

import Wrapper from '@/app/wrapper';
import Layout from '@/components/layout';

const poppins = Poppins({
  subsets: ['latin-ext'],
  weight: ['400', '500', '700', '900'],
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  modal,
  children,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={poppins.className}>
          <Wrapper>
            <Layout>
              {modal}
              {children}
            </Layout>
          </Wrapper>
        </body>
      </UserProvider>
    </html>
  );
}
